[package]
name = "part_2"
version = "0.1.0"
authors = ["fengjianlin <fengjianlin@moyi365.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solution = { path = "../solution" }
rand = "0.8.4"