/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function sum(a: object, b: number): number
export declare function distance(a: number[], b: number[]): number
export declare function last(a: unknown[]): unknown
export class DistributionService {
  static setup(redisUri: string, mysqlUri: string): Promise<DistributionService>
  cronAssign(): Promise<void>
  lockVehicle(helperId: Id, vehicleId: Id): Promise<void>
}
