pub use solution::*;

mod num_rescue_boats;
mod median_finder;
mod pick_index;
mod corp_flight_bookings;
mod compare_version;
mod get_kth_from_end;
mod smallest_k;
mod search;
mod balanced_string_split;
mod find_maximized_capital;
mod full_justify;
mod chalk_replacer;
mod number_of_boomerangs;
mod find_peak_element;
mod find_words;
mod is_valid_sudoku;
mod split_list_to_parts;
mod is_power_of_three;
mod min_distance;
mod get_sum;
mod num_decodings;
mod path_sum;
mod find_min_moves;
mod compute_area;
mod find_repeated_dna_sequences;
mod summary_ranges;
mod number_to_words;
mod divide;
mod fizz_buzz;
mod peak_index_in_mountain_array;
mod count_and_say;
mod find_complement;
mod word_dictionary;
mod min_moves;
mod plus_one;
mod majority_element;
mod search_matrix;
mod next_greater_element;
mod remove_invalid_parentheses;
mod is_self_crossing;
mod distribute_candies;
mod trap_rain_water;
mod is_perfect_square;
mod longest_subsequence;
mod find_min_steps;
mod find_poisoned_duration;
mod k_inverse_pairs;
mod get_money_amount;
mod bulb_switch;
mod is_rectangle_cover;
mod max_product;
mod find_tilt;
mod integer_replacement;
mod shuffle;
mod buddy_strings;
mod original_digits;
mod poor_pigs;

pub struct Solution {}

impl Utility for Solution {}