pub use solution::*;

mod mincost_to_hire_worker;
mod get_maximum_consecutive;
mod minimum_moves;
mod alert_names;
mod autentication_manager;
mod die_simulator;
mod flip_cups;
mod alphabet_board_path;
mod balanced_string;
mod longest_wpi;
mod is_good_array;
mod number_or_pairs;
mod largest1_bordered_square;
mod find_solution;
mod max_average_ratio;
mod best_hand;
mod min_taps;
mod stone_game_ii;
mod circular_permutation;
mod minimum_operations;
mod minimum_swap;
mod max_score_words;
mod moves_to_make_zigzag;
mod merge_similar_items;
mod largest_local;
mod print_bin;
mod get_folder_names;
mod count_triplets;
mod min_operations_max_profit;
mod minimum_deletions;
mod brace_expansion_ii;
mod max_value;
mod minimum_recolors;
mod min_subarray;
mod find_longest_subarray;
mod count_subgraphs_for_each_diameter;
mod min_number_of_hours;
mod restore_matrix;
mod maximal_network_rank;
mod count_subarrays;
mod answer_queries;
mod check_palindrome_formation;
mod find_lex_smallest_string;
mod num_dup_digits_at_most_n;
mod convert_temperature;
mod best_team_score;
mod check_arithmetic_subarrays;
mod find_length_of_shortest_subarray;
mod find_subarrays;
mod shortest_common_supersequence;
mod count_vowel_strings;
mod max_width_of_vertical_area;
mod arithmetic_triplets;
mod mask_pii;
mod min_score_triangulation;
mod prev_perm_opt1;
mod merge_stones;

pub struct Solution {}

impl Utility for Solution {}